name: CI
on: pull_request
jobs:
  lint:
    name: Lint
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: PreTest
        run: npm run pretest
      - name: Lint (JavaScript)
        run: npm run test:lint
  unit-fork:
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    name: Unit Tests fork
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: PreTest
        run: npm run pretest
      - name: Headless Tests
        run: npm run test:polymer:local
  unit:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    name: Unit Tests
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: PreTest
        run: npm run pretest
      - name: tests
        run: npm run test:polymer:sauce
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_DESIRE2LEARN }}
          SAUCE_USERNAME: Desire2Learn
